---
title: "Untitled"
author: "Brendi Ang"
date: "12/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(colorspace)
library(geofacet)
library(lubridate)
library(showtext)
library(tsibble)
```

```{r, include=FALSE}
library(tidytuesdayR) 

# Load data from TidyTuesday data on GitHub
tuesdata <- tidytuesdayR::tt_load("2022-01-11")

# Read-in datasets
colony <- tuesdata$colony
stressor <- tuesdata$stressor
```

```{r}
stressor <- stressor %>% 
  # Filter to US states only 
  filter(!state %in% c("Other States", "United States")) %>% 
  # Correct grammatical error
  mutate(stressor = if_else(stressor == "Disesases", 
                            true = "Diseases",
                            false = stressor))

colony <- colony %>% 
  # Filter to US states only 
  filter(!state %in% c("Other States", "United States")) 
```

```{r}
# --- Add quarter to dataset
stressor <- stressor %>%
  mutate(qtr = case_when(
    str_detect(months, "January") ~ 1,
    str_detect(months, "April") ~ 2,
    str_detect(months, "July") ~ 3,
    str_detect(months, "October") ~ 4)
    ) %>% 
  relocate(qtr, .before = months)

colony <- colony %>% 
  mutate(qtr = case_when(
    str_detect(months, "January") ~ 1,
    str_detect(months, "April") ~ 2,
    str_detect(months, "July") ~ 3,
    str_detect(months, "October") ~ 4
  )) %>% 
  relocate(qtr, .before = months)
  
# --- Add year/qtr to the dataset

stressor <- stressor %>% 
  # Add year and quarter
  mutate(year_qtr = paste0(year, "/Q", qtr)) %>% 
  # Convert to date format
  mutate(date = tsibble::yearquarter(year_qtr)) %>% 
  relocate(c(date, year_qtr), .before = year) 

colony <- colony %>% 
  # Add year and quarter
  mutate(year_qtr = paste0(year, "/Q", qtr)) %>% 
  # Convert to date format
  mutate(date = tsibble::yearquarter(year_qtr)) %>% 
  relocate(c(date, year_qtr), .before = year) 
```

```{r}
# 45 unique states in dataset
states <- colony %>% distinct(state) %>% pull()

# Match 45 unique states in grid
grid <- geofacet::us_state_grid1 %>% filter(name %in% states)
```

```{r}
df <- stressor %>%
  mutate(stressor = case_when(
    stressor %in% c("Diseases", "Other", "Unknown") ~ "Diseases or other causes",
    TRUE ~ stressor
  )) %>%
  group_by(stressor, year_qtr, state) %>% 
  mutate(stress_pct = sum(stress_pct)) %>% 
  # Remove duplicate rows
  distinct() %>% 
  ungroup()
  

df <- df %>% 
  group_by(year_qtr, state) %>% 
  # Replace missing stress_pct with 0
  mutate(stress_pct = replace_na(stress_pct, 0)) %>%
  # Total stress_pct for each qtr
  # Proportion for each stressor for each qtr
  mutate(total = sum(stress_pct),
         prop = (stress_pct / total) * 100) %>% 
  ungroup()

# Add full date
df <- df %>% 
  mutate(full_date = lubridate::as_date(date))
```


```{r}
showtext::font_add_google(name = "Roboto Condensed", family = "Regular 400")
showtext::showtext_auto()
```

```{r}
# Palette for plot
bee_palette <- c("#f2e8d6", "#eeba19", "#ed8c00", "#cc5d00", "#4f331b")
```

```{r}
df %>% 
  # filter(state %in% c("California", "Hawaii")) %>% 
  ggplot(aes(x = full_date,
             y = prop,
             fill = stressor)) +
  geom_area(colour = "black",
            position = "fill",
            alpha = 0.9,
            size = 0.3) +
  facet_wrap(~ state) +
  scale_fill_manual(values = bee_palette) +
  scale_y_continuous(breaks = seq(0, 1, 0.5)) +
  scale_x_date(labels = function(x) zoo::format.yearqtr(x, "%Y/Q1"),
               breaks = "1 year") +
  labs(title = "Proportion of bee colonies affected by various stressors over the years",
       x = "Year/Quarter",
       y = "Proportion affected by stressor",
       fill = "Stressor",
       caption = "Source: Data from USDA | #TidyTuesday 2022 week 2") +
  guides(fill = guide_legend(nrow = 1, byrow = TRUE)) +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 15, angle = 90),
    axis.text.y = element_text(size = 15),
    axis.title.y = element_text(size = 25),
    axis.title.x = element_blank(),
    axis.ticks.y = element_blank(),
    legend.position = "bottom",
    legend.background = element_rect(fill = bee_palette[1], colour = "black"),
    legend.text = element_text(size = 15),
    panel.grid = element_blank(),
    panel.spacing.x = unit(0.25, units = "cm"),
    panel.border = element_blank(),
    plot.caption = element_text(hjust = 0, size = 18),
    plot.background = element_rect(fill = bee_palette[1]),
    strip.text.x = element_text(size = 16, colour = "white"),
    strip.background = element_rect(fill = "#4f331b"),
    text = element_text(family = "Regular 400"),
    plot.title = element_text(size = 30, hjust = 0.5),
    # Change size of caption
    ) 

ggsave("week-02-plot.png", width = 8, height = 6, units = "in")
```




